// app/layout.tsx
import type { Metadata } from "next";
import { Nunito } from 'next/font/google';
import "./globals.css";
import Providers from "@/app/Providers";
import { ThemeProvider } from "next-themes";
import HeaderWrapper from "@/components/shared/Header/HeaderWrapper";
import { Toaster } from 'sonner'

const nunito = Nunito({
    variable: '--font-nunito',
    subsets: ['cyrillic'],
    weight: ['400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body className={`${nunito.className} antialiased`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <Providers >
                <Toaster
                    closeButton
                    richColors
                    position="top-center"
                />
                <HeaderWrapper />
                {children}
            </Providers>
        </ThemeProvider>
        </body>
        </html>
    );
}
