// app/layout.tsx
import type { Metadata } from "next";
import { Nunito } from 'next/font/google';
import "./globals.css";
import Providers from "@/app/Providers";
import { ThemeProvider } from "next-themes";
import HeaderWrapper from "@/components/shared/Header/HeaderWrapper";
import { Toaster } from 'sonner'
import Script from "next/script";
import React from "react";

const nunito = Nunito({
    variable: '--font-nunito',
    subsets: ['cyrillic'],
    weight: ['400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {


    return (
        <html lang="en" suppressHydrationWarning>
        <body className={`${nunito.className} antialiased`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <Providers >
                <Toaster
                    closeButton
                    richColors
                    position="bottom-center"
                    toastOptions={{
                        style: { marginBottom: '20px' } // отступ от низа
                    }}
                />
                <HeaderWrapper />
                {children}
                <Script
                    src="https://telegram.org/js/telegram-web-app.js?57"
                    strategy="beforeInteractive"
                />
            </Providers>
        </ThemeProvider>
        </body>
        </html>
    );
}
